services:
  kernel.listener.search_listener:
    class: SumoCoders\FrameworkUserBundle\EventListener\SearchListener
    arguments:
      - @service_container
    tags:
      - { name: kernel.event_listener, event: search.search, method: onSearch }
  custom_user_manager:
    class: SumoCoders\FrameworkUserBundle\Model\FrameworkUserManager
    arguments:
      - @security.encoder_factory
      - @fos_user.util.username_canonicalizer
      - @fos_user.util.email_canonicalizer
      - @fos_user.entity_manager
      - SumoCoders\FrameworkUserBundle\Entity\User
  user.add.form.type:
    class: SumoCoders\FrameworkUserBundle\Form\AddUserType
    arguments:
      - fos_user.model_user.class
    tags:
      - { name: form.type, alias: framework_user_add }

# FOS User Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SumoCoders\FrameworkUserBundle\Entity\User
  service:
    user_manager: custom_user_manager

